# -*- mode: ruby -*-
# vi: set ft=ruby :

source 'https://rubygems.org'

gem 'berkshelf', '~> 7.0.2'
gem 'inspec', '~> 2.1.72'
gem 'kitchen-inspec', '~> 0.23.1'
gem 'rake'

group :integration do
  gem 'test-kitchen', '~> 1.21.2'
end

group :vagrant do
  gem 'kitchen-vagrant'
end

group :ec2 do
  gem 'kitchen-ec2', '~> 2.5.0'
end
