name 'rblx_consul'
maintainer 'Roblox Inc.'
maintainer_email 'bwise@roblox.com'
license 'All Rights Reserved'
description 'Installs/Configures rblx_consul'
long_description 'Installs/Configures rblx_consul'
version '0.1.0'
chef_version '>= 14.0'
issues_url 'https://github.com/Roblox/rblx_chef_infrastructure/issues'
source_url 'https://github.com/Roblox/rblx_chef_infrastructure/tree/master/cookbooks/rblx_consul'

supports 'ubuntu', '>= 14.04'
supports 'redhat', '>= 6.4'
supports 'centos', '>= 6.4'
