version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.6
    working_directory: ~/circleci-workflows
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circleci-workflows
  rubocop_linting_test:
    docker:
      - image: circleci/ruby:2.6
    working_directory: ~/circleci-workflows
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run Rubocop linting tests
          command: |
            bundle install
            rspec 'spec/lint/ruby/run_rubocop.rb'
  foodcritic_linting_test:
    docker:
      - image: circleci/ruby:2.6
    working_directory: ~/circleci-workflows
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run Foodcritic linting tests
          command: |
            bundle install
            rspec 'spec/lint/chef/run_foodcritic.rb'
  testing_common: &testing_common
    #parallelism: 4
    docker:
      - image: circleci/ruby:2.6
    working_directory: ~/circleci-workflows
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Get Dependencies and Run Kitchen tests
          command: |
            cd cookbooks/$COOKBOOK
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --without=vagrant
            bundle exec rake integration:ec2[$FILTER]
  consul_test:
    <<: *testing_common
    environment:
      COOKBOOK: "rblx_consul"
      FILTER: "default-"
  golang_test:
    <<: *testing_common
    environment:
      FILTER: "default-"
      COOKBOOK: "rblx_golang"
  nomad_test:
    <<: *testing_common
    environment:
      FILTER: "default-"
      COOKBOOK: "rblx_nomad"
  vault_test:
    <<: *testing_common
    environment:
      FILTER: "."
      COOKBOOK: "rblx_vault"
  finalize_testing:
    docker:
      - image: circleci/ruby:2.6
    working_directory: ~/circleci-workflows
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Finished
          command: |
            echo "All done with Kitchen Testing!"
  grocery_delivery_common: &grocery_delivery_common
    parallelism: 4
    docker:
      - image: circleci/ruby:2.6
    working_directory: ~/circleci-workflows
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Grocery Delivery Dependencies
          command: |
            sudo apt-get update -y && sudo apt-get install cmake -y
            cd grocery_delivery
            bundle install
            cd  ../
            mkdir /home/circleci/cookbooks
      - run:
          name: Run Grocery Delivery
          command: |
            echo "Extra: $GDEXTRA"
            echo $CHEF_PRIVATE_KEY | base64 --decode >> /home/circleci/chef_private
            chmod 400 /home/circleci/chef_private
            chown circleci:circleci /home/circleci/chef_private
            grocery-delivery -l /var/lock/grocery_delivery.lock --pidfile /var/tmp/gd.pid --config-file ~/circleci-workflows/grocery_delivery/gd-config.rb $GDEXTRA
            echo "Removing PassKey"
            rm /home/circleci/chef_private
  grocery_delivery_dry:
    <<: *grocery_delivery_common
    environment:
      GDEXTRA: -v -v -n
  grocery_delivery:
    <<: *grocery_delivery_common
    environment:
      GDEXTRA: -v

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - rubocop_linting_test:
          requires:
            - checkout_code
      - foodcritic_linting_test:
          requires:
            - checkout_code
      - consul_test:
          requires:
            - rubocop_linting_test
            - foodcritic_linting_test
      # # # - golang_test:
      # # #     requires:
      # # #       - rubocop_linting_test
      # # #       - foodcritic_linting_test
      # # - nomad_test:
      # #     requires:
      # #       - rubocop_linting_test
      # #       - foodcritic_linting_test
      # # - vault_test:
      # #     requires:
      # #       - rubocop_linting_test
      # #       - foodcritic_linting_test
      # - finalize_testing:
      #      requires:
      #         - checkout_code
      #         # - consul_test
      #         # #- golang_test
      #         # - nomad_test
      #         # - vault_test
      # - grocery_delivery_dry:
      #    requires:
      #      - finalize_testing
      # - grocery_delivery:
      #     requires:
      #       - finalize_testing
      #       - grocery_delivery_dry
      #     filters:
      #       branches:
      #         only:
      #           - master