version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/circleci-workflows
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circleci-workflows
  consul_test:
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/circleci-workflows
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Get Dependencies and Run Kitchen tests
          command: |
            cd cookbooks/rblx_consul
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --without=vagrant
            bundle exec rake integration:ec2[default-ubuntu-1604]
  golang_test:
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/circleci-workflows
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Get Dependencies
          command: |
            cd cookbooks/rblx_golang
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --without=vagrant
            bundle exec rake integration:ec2[default-ubuntu-1604]
  vault_test:
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/circleci-workflows
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Get Dependencies
          command: |
            cd cookbooks/rblx_vault
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --without=vagrant
            bundle exec rake integration:ec2[default-ubuntu-1604] 
  finalize:
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/circleci-workflows
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Finished
          command: |
            echo "All done with Kitchen Testing!"
workflows:
  version: 2
  tests:
    jobs:
      - checkout_code
      - consul_test:
          requires:
            - checkout_code
      - golang_test:
          requires:
            - checkout_code
      - vault_test:
          requires:
            - checkout_code
      - finalize:
          requires:
            - consul_test
            - golang_test
            - vault_test
