version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/circleci-workflows
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circleci-workflows
  rubocop_linting_test:
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/circleci-workflows
    branches:
      only:
        - master
        - /feature\/.*/
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run Rubocop linting tests
          command: |
            bundle install
            rspec 'spec/lint/ruby/run_rubocop.rb'
  foodcritic_linting_test:
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/circleci-workflows
    branches:
      only:
        - master
        - /feature\/.*/
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run Foodcritic linting tests
          command: |
            bundle install
            rspec 'spec/lint/chef/run_foodcritic.rb'
  consul_test:
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/circleci-workflows
    branches:
      only:
        - master
        - /feature\/.*/
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Get Dependencies and Run Kitchen tests
          command: |
            cd cookbooks/rblx_consul
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --without=vagrant
            bundle exec rake integration:ec2[default-]
  golang_test:
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/circleci-workflows
    branches:
      only:
        - master
        - /feature\/.*/
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Get Dependencies
          command: |
            cd cookbooks/rblx_golang
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --without=vagrant
            bundle exec rake integration:ec2[default-]
  nomad_test:
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/circleci-workflows
    branches:
      only:
        - master
        - /feature\/.*/
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Get Dependencies
          command: |
            cd cookbooks/rblx_nomad
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --without=vagrant
            bundle exec rake integration:ec2[default-]
  vault_test:
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/circleci-workflows
    branches:
      only:
        - master
        - /feature\/.*/
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Get Dependencies
          command: |
            cd cookbooks/rblx_vault
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --without=vagrant
            bundle exec rake integration:ec2[.]
  finalize:
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/circleci-workflows
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Finished
          command: |
            echo "All done with Kitchen Testing!"
workflows:
  version: 2
  tests:
    jobs:
      - checkout_code
      - rubocop_linting_test:
          requires:
            - checkout_code
      - foodcritic_linting_test:
          requires:
            - checkout_code
      - consul_test:
          requires:
            - rubocop_linting_test
            - foodcritic_linting_test
      - golang_test:
          requires:
            - rubocop_linting_test
            - foodcritic_linting_test
      - nomad_test:
          requires:
            - rubocop_linting_test
            - foodcritic_linting_test
      - vault_test:
          requires:
            - rubocop_linting_test
            - foodcritic_linting_test
      - finalize:
          requires:
            - consul_test
            - golang_test
            - nomad_test
            - vault_test
